system:
    CUDA_VISIBLE_DEVICES: '0'
    GPU_memory_fraction: 0.5
    num_cpu: 10
    random_seed: 1

log:
    result_dir: './result/'

model:  
    name: 'simple_cnn_sigmoid'

optimizer:
    lr: 0.001 # default: +1e-3

train:
    epochs: 50
    batch_size: 2560

validation:
    batch_size: 2560

dataset:
    dir: ''
    csv_renji: './configs/renji1000.txt'
    data_type: '3hos_renji'
    input_dim: [50, 50, 1]  # HWC
    stride: 25
    load: 'ori'


